import {firestore} from 'firebase-admin';
import Timestamp = firestore.Timestamp;

export type UserData = {
  autoGeneratedPassPhrase: string,
}
export type UserPackages = {
  createdAt: Timestamp,
  history?: Array<UserPackages>,
  type: string,
}
